import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Beserrovsky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Beserrovsky's personal website!
        </h1>

        <p className={styles.description}>
          Wait... That's me!!!!
        </p>

        <div className={styles.grid}>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Beserrovsky/Beserrovsky"
          target="_blank"
          rel="noopener noreferrer"
        >
          Source code!
        </a>
      </footer>
    </div>
  )
}

export default Home
